"""'test_2'

Revision ID: df1b03e2eaf2
Revises: 1a592997f580
Create Date: 2021-08-27 01:22:22.301024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1b03e2eaf2'
down_revision = '1a592997f580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_column('student', 'first_name')
    op.drop_column('student', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('student', 'name')
    # ### end Alembic commands ###
